name: Ozark Pappy
favicon: null
layout_spectrum: 0.5004984494298697
typography_spectrum: 0.04470522026531398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9523651353083551
  lightness: 0.1002500201575458
  saturation: 0.4988013820257038
  rhythmicContrast: 0.29341838718391955
purpose: []
