name: Ozark Pappy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24962
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9d979b'
    - '#f2f1f8'
    - '#c3bec2'
    - '#5f5a60'
    - '#070608'
  brandStrength: 0.9523651353083551
  lightness: 0.1002500201575458
  saturation: 0.4988013820257038
  rhythmicContrast: 0.29341838718391955
purpose: []
